# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: ${CONTEXT_PATH:/}
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  application:
    name: cassiopeia-admin
  profiles:
    active: cassiopeia,cassiopeia-storage,cassiopeia-authentication,druid,redis
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: ${MAX_SIZE_PER_FILE:10MB}
      # 设置总上传的文件大小
      max-request-size: ${MAX_SIZE_PER_REQUEST:20MB}
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: ${RESTART_ENABLE:true}

# 日志配置
logging:
  config: classpath:logback-spring.xml

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: ${SWAGGER_ENABLE:true}
  # 请求前缀
  pathMapping: /api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: ${XSS_ENABLE:true}
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
